### ISSUE TITLE
Change.value at and Change value

### ISSUE THREAD

**Issue by Keevle** [gamestdio/colyseus-construct3#3]
![construct listen change](https://i.imgur.com/MTMuRXr.png)
```js
        if (change.operation === "add") {
          var dom = document.createElement("div");
          dom.className = "player";
          dom.style.left = change.value.x + "px";
          dom.style.top = change.value.y + "px";
          dom.style.background = colors[Math.floor(Math.random() * colors.length)];
          dom.innerHTML = `Player '${change.path.id}'`;

          players[change.path.id] = dom;
          document.body.appendChild(dom);

        } else if (change.operation === "remove") {
          document.body.removeChild(players[ change.path.id ]);
          delete players[change.path.id];
        }
```
 I was trying to translate some of the js client examples into c2 but noticed that a bunch of expressions are miss-well they appear to be missing to me,is this the case our am i just not understanding things correctly?

**Comment by endel** [comment]
Hi @Keevle, 

I haven't had a chance to test your C2 port yet. 

I've just checked listening for `"players/:id"` (using `Listen` condition), and I could get the player's initial `x` value by using the `Colyseus.ValueAt("x")` expression. (considering you're [connecting into the `"state_handler"` room](https://github.com/gamestdio/colyseus-examples/blob/master/rooms/02-state-handler.ts))

![screen shot 2018-04-29 at 00 28 12](https://user-images.githubusercontent.com/130494/39402937-46994976-4b44-11e8-9cff-e4ae9080159f.png)

Could it be that C2 has some runtime differences? Cheers!

**Comment by endel** [comment]
I've just tested on C2 and it worked exactly as C3 does.

One caveat, though: listening for `players/:id` will listen only for the addition or removal of that entity. To listen for its property changes, you'd need to listen for `players/:id/:attribute`, or directly, via `players/:id/x` and `players/:id/y`.

To get those attributes, you'd need to use the `Path` expresision:
- `Colyseus.Path("id")` - returns the player id (the value for the `:id` segment you're listening to)
- `Colyseus.Path("attribute")` - returns the attribute that has changed, `x` or `y` (in case you listened for `players/:id/:attribute`)

I don't really know how to map objects created on Construct by an id string, though. Do you have some idea? It would be necessary to have a way to retrieve object instances by id to operate in them, and apply changes.

**Comment by Keevle** [comment]
Ahh ok and yes all objects in c2/c3 store a UID in every object, so you can operate on something like 
![](https://i.imgur.com/Lrsh1dr.png)
But UID itself is a number the only way you could get a id string is if you use a coustom instance variable then just use that as a identifier @endel
